name = "marvelsnap"
main = "dist/index.js"
compatibility_date = "2025-12-10"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[triggers]
crons = ["0 19 * * *"]

[[kv_namespaces]]
binding = "MARVEL_SNAP_HUB"
id = "f0db931b10c848eda7dee99f1c106a19"
preview_id = "f0db931b10c848eda7dee99f1c106a19"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[d1_databases]]
binding = "DB"
database_name = "snap_nexus_db"
database_id = "3b63431f-5423-4098-bf1f-0ef92826a259"

[build]
command = "npm run build"
