name = "snapnexus"
pages_build_output_dir = "app/public"
compatibility_date = "2025-10-08"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "MARVEL_SNAP_HUB"
id = "f0db931b10c848eda7dee99f1c106a19"
preview_id = "f0db931b10c848eda7dee99f1c106a19"
remote = true

[[d1_databases]]
binding = "DB"
database_name = "snap_nexus_db"
database_id = "3b63431f-5423-4098-bf1f-0ef92826a259"
remote = true
